### ISSUE TITLE
cl-lsp won't install under SBCL 2.1.2 on MacOS M1

### ISSUE THREAD

**Issue by bpecsek** [cxxxr/lsp-server#13]
I've been trying to install cl-lsp in ros with sbcl 2.1.2 to use vscode but it fails to install due to the missing SB-KERNEL:%SIMPLE-FUN-NEXT function in the latest sbcl.

Is there a fix for this?

Since I'm using M1 MacOS and the only version supporting Arm64 Mac  is SBCL 2.1.2 I would need a fix for this.

On Linux it is the same but over there, installing sbcl 2.1.0 eliminates the problem, however, a fix would be good there too to be able to use the latest sbcl version.

I think this issue is present in prepl as well.

**Comment by cxxxr** [comment]
Sorry I have not been able to reply.
This issue has probably been resolved.
