### ISSUE TITLE
Does not install with Roswell on Arch Linux

### ISSUE THREAD

**Issue by fvckpvtin** [cxxxr/lsp-server#25]
Brand new install in April 2023. Tried to install via instructions on the website:

λ ros install lem-project/lem cxxxr/cl-lsp
Installing sbcl-bin...
No SBCL version specified. Downloading sbcl-bin_uri.tsv to see the available versions...
[##########################################################################]100%
Installing sbcl-bin/2.3.3...
Downloading https://github.com/roswell/sbcl_bin/releases/download/2.3.3/sbcl-2.3.3-x86-64-linux-binary.tar.bz2
[##########################################################################]100%
Extracting sbcl-bin-2.3.3-x86-64-linux.tar.bz2 to /home/ghost/.roswell/src/sbcl-2.3.3-x86-64-linux/
Building sbcl-bin/2.3.3... Done.
Install Script for sbcl-bin...
Installing Quicklisp... Done 19968
Making core for Roswell...
Installing from github lem-project/lem
To load "lem":
  Load 1 ASDF system:
    lem
; Loading "lem"
To load "inquisitor":
  Load 3 ASDF systems:
    alexandria anaphora asdf
  Install 1 Quicklisp release:
    inquisitor
Downloading http://beta.quicklisp.org/archive/inquisitor/2019-05-21/inquisitor-20190521-git.tgz
##########################################################################
; Loading "inquisitor"
[package inquisitor.encoding.dfa].................
[package inquisitor.encoding.table]...............
..................................................
[package inquisitor.encoding.guess]...............
[package inquisitor.eol]..........................
[package inquisitor.names]........................
[package inquisitor.external-format]..............
[package inquisitor.util].........................
[package inquisitor].
To load "lem":
  Load 1 ASDF system:
    lem
; Loading "lem"
To load "bordeaux-threads":
  Load 2 ASDF systems:
    alexandria asdf
  Install 1 Quicklisp release:
    bordeaux-threads
Downloading http://beta.quicklisp.org/archive/bordeaux-threads/2022-07-07/bordeaux-threads-v0.8.8.tgz
##########################################################################
; Loading "bordeaux-threads"
[package bordeaux-threads]...
To load "lem":
  Load 1 ASDF system:
    lem
; Loading "lem"
To load "yason":
  Load 3 ASDF systems:
    alexandria asdf trivial-gray-streams
  Install 1 Quicklisp release:
    yason
Downloading http://beta.quicklisp.org/archive/yason/2023-02-14/yason-20230214-git.tgz
##########################################################################
; Loading "yason"
[package yason]......
To load "lem":
  Load 1 ASDF system:
    lem
; Loading "lem"
To load "log4cl":
  Load 2 ASDF systems:
    asdf bordeaux-threads
  Install 1 Quicklisp release:
    log4cl
Downloading http://beta.quicklisp.org/archive/log4cl/2021-12-09/log4cl-20211209-git.tgz
##########################################################################
; Loading "log4cl"
[package log4cl.package-setup]....................
[package log4cl-impl]....[1/3] System 'lem' found. Loading the system..
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Lock on package SB-C violated when interning LAMBDA-PARENT while in package
;     LOG4CL-IMPL.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;
;     (in form starting at line: 99, column: 0, position: 3779)
Aborted during step [1/3].
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD tid=17237 "main thread" RUNNING
                                                          {10010A8113}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">

Backtrace for: #<SB-THREAD:THREAD tid=17237 "main thread" RUNNING {10010A8113}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1004B7A8B3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1004B7A8B3}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1004B7A8B3}>)
3: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">)))
4: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">)))
5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">)
6: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
7: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "log4cl" "src" "naming-sbcl">) [fast-method]
8: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002957403}>) [fast-method]
9: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
10: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002957403}>) [fast-method]
11: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "log4cl"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
12: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "log4cl"> :VERBOSE NIL)
13: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
14: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "log4cl"> :VERBOSE NIL) [fast-method]
15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "log4cl" :VERBOSE NIL)
16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "log4cl" :VERBOSE NIL) [fast-method]
18: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100289E0BB}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100289ACDB}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
21: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "log4cl" :VERBOSE NIL) [fast-method]
22: (ASDF/OPERATE:LOAD-SYSTEM "log4cl" :VERBOSE NIL)
23: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {100289AC4B}>)
24: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "log4cl" :PROMPT NIL)
25: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "lem" :PROMPT NIL)
26: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002EE73CB}>) [fast-method]
27: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1004AE8423}> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002EE73CB}>) [fast-method]
28: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) "lem" :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
29: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002EE29EB}>)
30: (INSTALL-SYSTEM-SCRIPT "lem")
31: (INSTALL-SYSTEM-IF-PROBED "lem")
32: (INSTALL ("cxxxr/cl-lsp"))
33: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
34: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
35: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL NIL)
36: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
37: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {10022F28A3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
38: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {10022F28A3}> NIL)
39: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7F1CC32DF5CB}> #<CONCATENATED-STREAM :STREAMS NIL {10022F28A3}> NIL #<CONCATENATED-STREAM :STREAMS NIL {10022F28A3}>)
40: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {10022F28A3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
41: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /etc/roswell/install.ros" {10022E79D3}>)
42: (ROSWELL:SCRIPT "/etc/roswell/install.ros" "lem-project/lem" "cxxxr/cl-lsp")
43: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:SCRIPT "/etc/roswell/install.ros" "lem-project/lem" "cxxxr/cl-lsp") (:QUIT NIL)))
44: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/etc/roswell/install.ros" "lem-project/lem" "cxxxr/cl-lsp") (:QUIT NIL)))) #<NULL-LEXENV>)
45: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/etc/roswell/install.ros" "lem-project/lem" "cxxxr/cl-lsp") (:QUIT NIL)))))
46: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:quicklisp)\")(:script \"/etc/roswell/install.ros\"\"lem-project/lem\"\"cxxxr/cl-lsp\")(:quit ())))")))
47: (SB-IMPL::TOPLEVEL-INIT)
48: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
49: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
50: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
;
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition

➜ ~
λ

Any ideas what may be the problem?

Thanks.

**Comment by cxxxr** [comment]
Probably this is the same problem.
https://github.com/lem-project/lem/issues/611#issuecomment-1522849443

**Comment by fvckpvtin** [comment]
This did indeed work. Thanks!
