### ISSUE TITLE
Formatting doesn't do anything

### ISSUE THREAD

**Issue by LordMZTE** [cxxxr/lsp-server#26]
I'm using the server in neovim; when I format, nothing happens.

This is printed to the log file:
```log
<INFO> [16:06:19] lem-language-server method.lisp (log-request) -
 textDocument/formatting: {"options":{"insertSpaces":true,"tabSize":4},"textDocument":{"uri":"file:///home/lordmzte/dev/clisp/coin_toss.lisp"}}
<INFO> [16:06:19] lem-language-server method.lisp (log-response) -
 textDocument/formatting: []
```

The code will remain unchanged even tho it has some very obvious improper formatting.

**Comment by cxxxr** [comment]
Thank you for reporting this.
Would it be possible for you to post the contents of the code here?

**Comment by LordMZTE** [comment]
Sure, here's some very badly formatted lisp code which doesn't change when formatting.

```lisp
(defpackage coin-toss
  (:use :cl)
  (:export toss-coin))
(in-package :coin-toss)

(defun toss-coin ()
  



  0)
```

Here's also how I configured `nvim-lspconfig` to use cl-lsp (in fennel). Might be useful.

```fennel
(tset lsp-configs :cl-lsp {:default_config {:cmd [:cl-lsp]
                                            :filetypes [:lisp]
                                            :root_dir lspc.util.find_git_ancestor
                                            :single_file_support true}
                           :settings {}})
(lspconfig.cl-lsp.setup {})
```

**Comment by cxxxr** [comment]
Thank you very much.
Is the expected behavior to remove whitespace?
The current behavior only does line indentation.

**Comment by LordMZTE** [comment]
Oh I see, I was expecting removal of many consecutive lines and also split up long lines.

Indentation appears to work.

**Comment by cxxxr** [comment]
Ideally, it would be better to remove the blanks as well.
Thanks for the feedback.
